name: Build and deploy project Django-ch to Kubernetes

on:
  push:
    branches: ["main"]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Build & Push image
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |   
          docker build . -t intellare/django-ch:${SHORT_SHA}
          docker push intellare/django-ch:${SHORT_SHA}

  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [release]
    steps:
    - uses: actions/checkout@master
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    - name: deploy to cluster
      uses: WyriHaximus/github-action-helm3@v3
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
      with:
        kubeconfig: '${{ secrets.KUBECONFIG }}'
        overrule_existing_kubeconfig: "true"
        exec: helm upgrade --install django-ch ./helm -f ./helm/values.yaml --set image.tag=${SHORT_SHA} --set db.name=${{ secrets.POSTGRES_NAME }} --set db.host=${{ secrets.POSTGRES_HOST }} --set db.port=${{ secrets.POSTGRES_PORT }} --set db.user=${{ secrets.POSTGRES_USER }} --set db.pass=${{ secrets.POSTGRES_PASSWORD }}  --namespace apps
